version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building the project..."
      - run: |
          if [ -f index.html ]; then
            echo "Build successful!"
          else
            echo "Build failed: index.html not found."
            exit 1
          fi
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
